server:
  port: 8761
  
spring:
  profiles:
    active: dev
  application:
    name: eureka-server
    
eureka:
  instance:
    hostname: otracosa
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://otracosa:${server.port}/eureka/
